# Generated by Django 4.1.2 on 2022-10-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_place_image_alter_placestovisit_image'),
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='places',
            field=models.ManyToManyField(to='travel.place'),
        ),
    ]
