# Generated by Django 4.1.2 on 2022-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('IN', 'International'), ('DM', 'Domestic')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
