# Generated by Django 4.1.2 on 2022-10-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place_category_place_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='places_to_visit',
            field=models.JSONField(null=True),
        ),
    ]
