# Generated by Django 4.1.2 on 2022-10-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_place_places_to_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='places_to_visit',
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='landscape.jpg', upload_to='places'),
        ),
        migrations.CreateModel(
            name='PlacesToVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='landscape.jpg', upload_to='places')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.place')),
            ],
        ),
    ]
