# Generated by Django 4.1.2 on 2022-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_place_image_alter_placestovisit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='landscape.jpg', upload_to='places'),
        ),
        migrations.AlterField(
            model_name='placestovisit',
            name='image',
            field=models.ImageField(default='landscape.jpg', upload_to='places'),
        ),
    ]
